/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import CapaLogica.Profesores;

/**
 *
 * @author alons
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setSize(680, 415);
        this.setLocationRelativeTo(null);
        Ocultar();
        paneltitulos.setVisible(true);
    }
    
    public void Ocultar(){
        //OBJETOS DE PROFESORES
        panelprofesores.setVisible(false);
        paneltitulos.setVisible(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelprofesores = new javax.swing.JPanel();
        LBidp = new javax.swing.JLabel();
        LBnombrep = new javax.swing.JLabel();
        LBgradop = new javax.swing.JLabel();
        LBsueldop = new javax.swing.JLabel();
        LBtitulop = new javax.swing.JLabel();
        TFidp = new javax.swing.JTextField();
        TFnombrep = new javax.swing.JTextField();
        TFgradop = new javax.swing.JTextField();
        TFsueldop = new javax.swing.JTextField();
        BTlimpiarp = new javax.swing.JButton();
        BTinsertarp = new javax.swing.JButton();
        BTeliminarp = new javax.swing.JButton();
        paneltitulos = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        menu = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelprofesores.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        panelprofesores.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LBidp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LBidp.setText("ID DEL PROFESOR");
        panelprofesores.add(LBidp, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 76, -1, -1));

        LBnombrep.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LBnombrep.setText("NOMBRE ");
        panelprofesores.add(LBnombrep, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        LBgradop.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LBgradop.setText("GRADO");
        panelprofesores.add(LBgradop, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, -1, -1));

        LBsueldop.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LBsueldop.setText("SUELDO");
        panelprofesores.add(LBsueldop, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        LBtitulop.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        LBtitulop.setText("FORMULARIO GENERAL");
        panelprofesores.add(LBtitulop, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 11, -1, -1));

        TFidp.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TFidp.setMinimumSize(new java.awt.Dimension(200, 28));
        TFidp.setPreferredSize(new java.awt.Dimension(200, 28));
        panelprofesores.add(TFidp, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 73, -1, -1));

        TFnombrep.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TFnombrep.setMinimumSize(new java.awt.Dimension(200, 28));
        TFnombrep.setPreferredSize(new java.awt.Dimension(200, 28));
        panelprofesores.add(TFnombrep, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, -1, -1));

        TFgradop.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TFgradop.setMinimumSize(new java.awt.Dimension(200, 28));
        TFgradop.setPreferredSize(new java.awt.Dimension(200, 28));
        panelprofesores.add(TFgradop, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, -1, -1));

        TFsueldop.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        TFsueldop.setMinimumSize(new java.awt.Dimension(200, 28));
        TFsueldop.setPreferredSize(new java.awt.Dimension(200, 28));
        panelprofesores.add(TFsueldop, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, -1, -1));

        BTlimpiarp.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        BTlimpiarp.setText("LIMPIAR");
        panelprofesores.add(BTlimpiarp, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, -1, -1));

        BTinsertarp.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        BTinsertarp.setText("INSERTAR");
        BTinsertarp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTinsertarpActionPerformed(evt);
            }
        });
        panelprofesores.add(BTinsertarp, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 120, -1, -1));

        BTeliminarp.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        BTeliminarp.setText("ELIMINAR");
        BTeliminarp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTeliminarpActionPerformed(evt);
            }
        });
        panelprofesores.add(BTeliminarp, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 170, -1, -1));

        getContentPane().add(panelprofesores, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 390));

        paneltitulos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setText("PACTICA 1.3");
        paneltitulos.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("CLAUDIO ALONSO DOMINGUEZ ROMAN");
        paneltitulos.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 480, -1));

        getContentPane().add(paneltitulos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 680, 140));

        jMenu1.setText("PROFESORES");

        jMenuItem7.setText("INICIO");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem7);

        jMenuItem1.setText("FORMULARIO");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("CONSULTA");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        menu.add(jMenu1);

        jMenu2.setText("MATERIAS");

        jMenuItem3.setText("FORMULARIO");
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("CONSULTA");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        menu.add(jMenu2);

        jMenu3.setText("OTRAS CONSULTA");

        jMenuItem5.setText("PROFESORES CON DOS MATERIAS");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem5);

        jMenuItem6.setText("GRADO ACADEMICO DE LOS PROFEESORES");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem6);

        menu.add(jMenu3);

        setJMenuBar(menu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        Ocultar();
        panelprofesores.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        Ocultar();
        paneltitulos.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void BTinsertarpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTinsertarpActionPerformed
        // TODO add your handling code here:
        Profesores P = new Profesores(TFidp.getText(),TFnombrep.getText(),TFgradop.getText(),Double.parseDouble(TFsueldop.getText()));
        P.InsertaProfesores(P);
    }//GEN-LAST:event_BTinsertarpActionPerformed

    private void BTeliminarpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTeliminarpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BTeliminarpActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTeliminarp;
    private javax.swing.JButton BTinsertarp;
    private javax.swing.JButton BTlimpiarp;
    private javax.swing.JLabel LBgradop;
    private javax.swing.JLabel LBidp;
    private javax.swing.JLabel LBnombrep;
    private javax.swing.JLabel LBsueldop;
    private javax.swing.JLabel LBtitulop;
    private javax.swing.JTextField TFgradop;
    private javax.swing.JTextField TFidp;
    private javax.swing.JTextField TFnombrep;
    private javax.swing.JTextField TFsueldop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuBar menu;
    private javax.swing.JPanel panelprofesores;
    private javax.swing.JPanel paneltitulos;
    // End of variables declaration//GEN-END:variables
}
